# Generated by Django 4.1.7 on 2023-09-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asana', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asana',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='asana',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
